### ISSUE TITLE
Path must be a string. Received null 

### ISSUE THREAD

**Issue by carlotrimarchi** [hollandben/grunt-cache-bust#219]
Hello,
I'm receiving this error:

```
Warning: Path must be a string. Received null Use --force to continue.
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at Object.hasExtension (/node_modules/grunt-cache-bust/tasks/lib/utils.js:45:21)
    at Object.checkIfValidFile (/node_modules/grunt-cache-bust/tasks/lib/utils.js:53:18)
    at Object.checkIfElemContainsValidFile (/node_modules/grunt-cache-bust/tasks/lib/utils.js:
75:32)
    at Object.<anonymous> (/node_modules/grunt-cache-bust/tasks/lib/findStaticAssets.js:58:42)
    at testFn (/node_modules/cheerio/lib/api/traversing.js:314:22)
    at filter (/node_modules/cheerio/node_modules/lodash/dist/lodash.js:3151:15)
    at module.exports.filter (/node_modules/cheerio/lib/api/traversing.js:324:28)
    at addPaths (/node_modules/grunt-cache-bust/tasks/lib/findStaticAssets.js:57:26)

Aborted due to warnings.
```

I don't understand what is it referring to. Any help?

**Comment by carlotrimarchi** [comment]
I managed to solve by upgrading grunt-cache-bust and consequently grunt.
